### ISSUE TITLE
Outputting the Github rate limit info to the activity log of the plugin

### ISSUE THREAD

**Issue by gonzague** [patrickposner/simply-static#116]
Hello!

Currently trying to use your plugin with Github and Cloudflare Pages but I was wondering why it was stuck at 
`[2023-02-23 11:19:13] Mise en place
[2023-02-23 11:19:28] 3141 pages/fichiers sur 3141 générés
[2023-02-23 12:29:17] Starts to transfer pages/files to GitHub`

When I turned on diagnostics / I found numerous lines such as this
`[2023-02-23 13:09:01] [class-ssp-github-database.php:143] You have reached GitHub hourly limit! Actual limit is: 5000`

Might make sense to output it to the activity log of the plugin because otherwise you just dont know why it is / seems stuck?

thanks

**Comment by gonzague** [comment]
and additional thought : maybe a way to throttle the requests made by the plugin to GitHub to avoid this problem when it arises

**Comment by patrickposner** [comment]
Hey @gonzague, thanks for bringing that up!

This is already in development. With the next major release of Simply Static Pro, there will be both - throttling for requests to avoid the limit (there is already one for the secondary API limit, but not for the hard limit) and information in the log explaining why we have to wait for X seconds/minutes before continuing export.

I'm closing this issue here as this is dedicated to Simply Static Pro, but I wanted to explain you!

Cheers,
Patrick
