### ISSUE TITLE
ZIP download link not working

### ISSUE THREAD

**Issue by shot-codes** [patrickposner/simply-static#117]
After generating the link, the "click here to download" button isn't working: It does not download a zip and instead sends me to an html page. I right click and say donwload linked file I download a file `https://mysite.com/www/wp-content/plugins/simply-static/static-files/simply-static-1-1677439084.zip.html`. If I change the file extension and try to uncompress the zip it complains that it is not in the correct format.

**Comment by patrickposner** [comment]
Hey @shot-codes,

thanks for reaching out!

That sounds more like a filesystem problem than a problem within Simply Static.
Check Simply Static -> Diagnostics -> Temporary Directory - is it writeable?

You can also change the directory's path in Simply Static -> Settings -> Advanced.
 If some security restrictions are in place preventing creating the directory and zipping it.

Also, make sure that "zlip" is installed on your server so that Simply Static can create the zip file.
