### ISSUE TITLE
Generate static site not working with version 2.2.7

### ISSUE THREAD

**Issue by kirankc** [patrickposner/simply-static#118]
Not sure if it's something to do with removing the wp-cron, but the new version is not working when clicking on generate static site. The debug log just says that a request to generate the static site started but nothing after. Removing and adding the plugin has no effect. Had to revert back to version 2.2.6 to get it working again.

**Comment by patrickposner** [comment]
Hey @kirankc,

thanks for reaching out!

Wp-Cron is now the default when using Simply Static (that's why the option was removed).
I assume it has something to do with WP-Cron not running on your server.

This can happen if:

- DISABLE_WP_CRON is defined and set to true
- the server blocks WP-Cron
- WP-Cron was replaced with a UNIX cron

If you use a UNIX cron, you should define SS_CRON and set it to true in the wp-config.php to make sure everything works as expected again.
