### ISSUE TITLE
"WP_Background_Process" error when activating plugin

### ISSUE THREAD

**Issue by o-r-i-z-u-r-u** [patrickposner/simply-static#126]
I downloaded master.zip manually and pasted to the plugins folder
then in wp plugins I click "activate" and up pops this error:

>Fatal error: Uncaught Error: Class "WP_Background_Process" not found in  
>\wordpress\wp-content\plugins\simply-static\src\class-ss-archive-creation-job.php:14 Stack trace: #0 
>\wordpress\wp-content\plugins\simply-static\src\class-ss-plugin.php(172): require_once() #1  
>\wordpress\wp-content\plugins\simply-static\src\class-ss-plugin.php(89): Simply_Static\Plugin->includes()  ......etc.

Any pointers?

**Comment by patrickposner** [comment]
Hey @o-r-i-z-u-r-u,

that's because the version of Simply Static hosted here is not an installable WordPress plugin :-)

If you want to use it, you need [composer](https://getcomposer.org/) to download the dependencies first.
So switch into the directory via the terminal and run "composer update" to install the dependencies.
