### ISSUE TITLE
Github Multiple Commits

### ISSUE THREAD

**Issue by MattHadfield113** [patrickposner/simply-static#14]
When using the github integration, its pushing each file, one by one, causing hundreds of builds into the pipeline rather than a single commit with all files included. We pushed nearly 300 files on our site, leaving a build queue of around 24 hours on Cloudflare Pages.

**Comment by K-Mazur** [comment]
Hi @MattHadfield113 , did you find any solution?

**Comment by patrickposner** [comment]
To prevent that I introduced webhook support now: [https://patrickposner.dev/docs/simply-static/github/#Webhooks](https://patrickposner.dev/docs/simply-static/github/#Webhooks)
It will trigger the webhook once all files are committed to your repository.

**Comment by Dev3lopDev** [comment]
@patrickposner love the plugin.

I'm running into this same experience but with 3000 files, as you can imagine thats an insane amount of commits.  Is there a hard limitation driving the choice to commit each file one by one to github rather than do it as a single commit?

I don't want to open an issue and waste your time.

**Comment by patrickposner** [comment]
@Dev3lopDev, thanks for your follow-up!

That's no longer the case since version 1.2.4.
I completely rewrote the entire API integration with the GitHub Database API: https://docs.github.com/en/rest/git?apiVersion=2022-11-28

This means there is only one single commit for an entire static export.
