### ISSUE TITLE
Are responsive images with srcset working?

### ISSUE THREAD

**Issue by patrickposner** [patrickposner/simply-static#49]
Original question: https://wordpress.org/support/topic/are-responsive-image-sizes-used/

**Comment by sgdavis1** [comment]
Hi Patrick! Love the plugin, definitely going to go Pro soon but want to make sure we don't have any kinks in the production usage before we commit to buy. 

One thing we are aware of is an issue with the dynamic issues and I am thinking it is related to the visual editor we are using possible. We are using Brizy as a visual editor on our "dev" site: https://dev.bioneos.com which will be the live WP version. If you navigate to our blog posts you can see that some of the images are using the dynamic image tags with "srcset" attributes that simply point back to the root of our domain with a query parameter that instructs brizy to perform some image manipulation. Example:

```
https://dev.bioneos.com/?brizy_media=4092&amp;brizy_crop=iW%3D888%26iH%3D500%26oX%3D272%26oY%3D0%26cW%3D344%26cH%3D500
```

When the static site is generated, it appears any of these image references that exist do not get translated into static images (or if they do -- the image file isn't save anywhere. I would suspect this is due to the URL and the fact that it looks like they are all referencing the main domain. If so, I'm not sure if we will need to put in a support request to Brizy to make a change or if you could handle it? I also imagine it could be those `srcset` attributes are not recognized / handled (hence this issue, and why I am posting this here).

Any thoughts on this?

**Comment by patrickposner** [comment]
This will now be covered in https://github.com/patrickposner/simply-static/issues/61
