### ISSUE TITLE
Github deployment fails silently

### ISSUE THREAD

**Issue by beauvais** [patrickposner/simply-static#65]
When running the generator, it fails to commit most of the files to the github repo (but does post _some_). When looking at the debugging log, I see this line repeated hundreds of times, before getting the success and wrap-up message (saying everything's been generated and posted to github):

`[class-ssp-github-database.php:139] Could not create a blob from the file. Check the file permissions.`

**Comment by patrickposner** [comment]
As the error message indicates, Simply Static cannot convert your files due to missing writing permissions in the temporary directory created in /wp-content/plugins/simply-static/static-files/ (if not modified within the settings).

By ensuring that Simply Static has read and write access to that folder (or by changing the directory to a folder with these capabilities), you can ensure that all files are committed to GitHub.

Closing that one as it does not belong to Simply Static but to Simply Static Pro.
