### ISSUE TITLE
Elementor Support: Incorrect path building leads to scripts not imported

### ISSUE THREAD

**Issue by pldelattre** [patrickposner/simply-static#80]
After exporting my site with simply static, I get several errors in chrome console like the following one : 

<img width="1290" alt="image" src="https://user-images.githubusercontent.com/19731392/211204647-1af9da60-7edb-442c-8582-b4ba854e9dfd.png">

We can see that the exported site is looking to find several scripts in 
.../wp-content/plugins/elementor/assets/**index.htmljs**/

Instead of 
.../wp-content/plugins/elementor/assets/**js**/

Everything is fixed when I copy n paste **js** folder and name it **index.htmljs** to satisfy incorrect links.

**Comment by igorbenic** [comment]
@pldelattre could you give a bit more information:

- Elementor version
- Is elementor Pro installed?
- Page setup (screenshot of video configuration from that landing page, guessing due to video file)
- Simply Static Settings - Destination

I was able to generate a static page with Elementor as the landing page without issues. All scripts seem to be fine and in the correct folder/file structure.

**Comment by pldelattre** [comment]
Hey ! 

- Elementor version 3.9.2
- Is pro installed ? No.
- Page setup => I'm just using the basic video widget from elementator
- Simply Static Settings - Destination =>  Use relative URLs (I just figured there is "save for offline use" option that I didn't use). I will try again with that option.

**Comment by pldelattre** [comment]
@igorbenic 

When using, the "save for offline use" option, path building seems correct. However, many scripts are not included in the JS folder :  

<img width="997" alt="image" src="https://user-images.githubusercontent.com/19731392/211789871-9403326f-b45f-40d1-a40a-53fc8a4256de.png">

**Comment by igorbenic** [comment]
@pldelattre thank you for the details.

I think I found the issue. Elementor is loading scripts conditionally, after the initial page load. Since Simply Static reads the page source (from the initial page load) such scripts are not found there and therefore not copied over.

As @patrickposner already said, an official integration with Elementor is now being worked on that should be able to copy all the bundled files from Elementor and put them in correct folders.

**Comment by akash-dbird** [comment]
When using Elementor header, it's not copying the scripts used in the header area.
